name: Update Dependencies
on:
  release:
    types:
      - published
  workflow_dispatch:
permissions:
  contents: write
jobs:
  opus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: "Install Opus Build Dependencies"
      run: "sudo apt-get install autoconf automake libtool gcc make"
    - name: "Clone Opus"
      run: "git clone https://gitlab.xiph.org/xiph/opus.git libs/libopus"
    - name: "Get Latest Version"
      run: "cd libs/libopus && echo \"OPUS_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)\" >> $GITHUB_ENV"
    - name: "Build Opus"
      run: "git checkout $OPUS_VERSION && ./autogen.sh && ./configure && make -j$(nproc) && cd .. && mv $(readlink -f libopus/.libs/libopus.so) libopus.so"
    - name: "Commit Opus"
      uses: EndBug/add-and-commit@v9
      with:
        add: "libs/libopus.so"
        default_author: github_actions
        message: Update libs/libopus.so to ${{ env.OPUS_VERSION }}